/**
 * Centralized Error Codes
 * Single source of truth for all error codes
 */

export const ERROR_CODES = {
  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  
  // Database Errors
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_QUERY_ERROR: 'DB_QUERY_ERROR',
  DB_TIMEOUT: 'DB_TIMEOUT',
  
  // Resource Errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  
  // Order Errors
  ORDER_CREATE_FAILED: 'ORDER_CREATE_FAILED',
  ORDER_UPDATE_FAILED: 'ORDER_UPDATE_FAILED',
  ORDER_DELETE_FAILED: 'ORDER_DELETE_FAILED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
  
  // Food Errors
  FOOD_CREATE_FAILED: 'FOOD_CREATE_FAILED',
  FOOD_UPDATE_FAILED: 'FOOD_UPDATE_FAILED',
  FOOD_DELETE_FAILED: 'FOOD_DELETE_FAILED',
  FOOD_NOT_FOUND: 'FOOD_NOT_FOUND',
  
  // Cart Errors
  CART_UPDATE_FAILED: 'CART_UPDATE_FAILED',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  
  // Admin Errors
  ADMIN_CREATE_FAILED: 'ADMIN_CREATE_FAILED',
  ADMIN_UPDATE_FAILED: 'ADMIN_UPDATE_FAILED',
  ADMIN_DELETE_FAILED: 'ADMIN_DELETE_FAILED',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  
  // Server Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
};

export default ERROR_CODES;
